---
title: "Assignment 4"
author: "Surya"
date: "2023-10-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(TTR)
library(fpp)
library(fpp2)
Monthly_Commodity_Prices_Time_Series_Dataset
oilprice <- Monthly_Commodity_Prices_Time_Series_Dataset
oilprice
```
```{r}
oilprice_ts <- ts(oilprice$oil_brent, start = 1, frequency = 1) #convert into timeseries and then start forecast
mean_forecast <- meanf(oilprice_ts,5)
plot(mean_forecast)
```
```{r}
#Naive Forecast
naive_forecast <- naive(oilprice_ts,5)
plot(naive_forecast)
```
```{r}
#Seasonal Naive Forecast
snaive_forecast <- snaive(oilprice_ts,5)
plot(mean_forecast)
lines(naive_forecast$mean, col= "red")
```
```{r}
#Random Walk Forecast
rwf_forecast <- rwf(oilprice_ts,5)
plot(rwf_forecast)
```
```{r}
#Plotting all together
plot(mean_forecast)
lines(naive_forecast$mean, line = "red")
lines(snaive_forecast$mean, line = "green")
lines(rwf_forecast$mean, line = "blue")
```
```{r}
#Attributes
attributes(naive_forecast)
attributes(snaive_forecast)
attributes(mean_forecast)
attributes(rwf_forecast)
```
```{r}
plot(oilprice,month.name)
lines(rwf_forecast$mean,col="green")
lines(snaive_forecast$mean,col="black")
lines(naive_forecast$mean,col="red")
```
```{r}
#Drift with RWF
plot.new()
rwf_forecast <- rwf(oilprice_ts,5, drift=TRUE)
lines(rwf_forecast$mean,col="green")
```
```{r}
#Moving Averages
plot.new()
MA5_forecast <- ma(oilprice_ts,order=5)
lines(MA5_forecast,col="Pink")
MA9_forecast <- ma(oilprice_ts,order=9)
lines(MA9_forecast,col="Blue")
```
```{r}
#Holtwinters and SSE
ets(oilprice_ts)
HoltWinters(oilprice_ts,beta = FALSE,gamma = FALSE)
SSE_Simple <- HoltWinters(oilprice_ts,beta=FALSE,gamma=FALSE)
attributes(SSE_Simple)
plot(SSE_Simple)
SSE_Simple$SSE
SSE_Simple$fitted
```
```{r}
#SSE with trend
SSE_Trend <- HoltWinters(oilprice_ts,gamma=FALSE)
plot(SSE_Trend)
SSE_Trend
attributes(SSE_Trend)
SSE_Trend$SSE
```
```{r}
SSE_Winters <- HoltWinters(oilprice_ts)
SSE_Winters$SSE
plot(SSE_Winters)
```
```{r}
ets(oilprice_ts)
ets_forecast <- ets(oilprice_ts)
attributes(ets)
attributes(ets_forecast)
ets_forecast$mse
```
```{r}
forecast.ets(ets_forecast, h=5)
forecast_ets <- forecast.ets(ets_forecast, h=5)
plot(forecast_ets)
accuracy(forecast_ets)
accuracy(mean_forecast)
accuracy(snaive_forecast)
accuracy(naive_forecast)
accuracy(rwf_forecast)
```

